### ISSUE TITLE
webpack 4

### ISSUE THREAD

**Issue by primozs** [faceyspacey/redux-first-router-boilerplate#16]
any webpack 4 example? somewhere
cheers

**Comment by valorloff** [comment]
Have you tried update to 4? Works ?

**Comment by primozs** [comment]
@valorloff hi
with upgrading redux-first-router components I did not have much issues

this could be good current example:
https://github.com/ScriptedAlchemy/redux-first-router-demo

if you are using also universal component this might be helpful
https://github.com/faceyspacey/react-universal-component/issues/175
cheers

**Comment by valorloff** [comment]
Thanks for the useful info, but in demo webpack also 3.x.x

**Comment by primozs** [comment]
this demo its a fork
https://github.com/ScriptedAlchemy/redux-first-router-demo/blob/master/package.json
 and as much as I see its 4.x

**Comment by valorloff** [comment]
may be need replace 
Installation
`git clone https://github.com/faceyspacey/redux-first-router-demo`
with
`git clone https://github.com/ScriptedAlchemy/redux-first-router-demo`
?
If i clone ScriptedAlchemy fork and start it, i get PAGE NOT FOUND - 404 and
`[FLUSH CHUNKS]: Unable to find default in Webpack chunks. Please check usage of Babel plugin.`
error
and you forgot import fetch in utils.js....
May I ask you up to date demo with webpack 4?
Thanks for your work!
